---
title: "Reading notes on Git in Practice by Mike McQuaid"
date: '2023-01-02'
slug: reading-notes-git-in-practice
output: hugodown::hugo_document
tags:
  - good practice
  - books
---

While preparing materials for teaching Git a few months ago, I re-read Suzan Baert's excellent [post about Git and GitHub](https://suzan.rbind.io/2018/03/reflections-4-months-of-github/), where she [mentioned](https://suzan.rbind.io/2018/03/reflections-4-months-of-github/#final-thoughts) having read "Git in Practice" by Mike McQuaid.
I added the book to my [Momox](https://en.wikipedia.org/wiki/Momox) alerts, where it got available a few weeks later.
Here are my reading notes, since I hope this habit of writing book learnings will stick.

## First impressions

### Manning Publications book cover

This is the second book published by Manning that I own, the other being "The Programmer's Brain" by Felienne Hermans.
Both have covers featuring an ancient drawing of someone wearing a traditional dress, but different drawings of course, and different artists.
For "Git in Practice" the cover is "A Kamtchadale in her full dress in 1768".
While the editor didn't explain why a particular drawing was chosen, they have a general explanation

> At a time when it is hard to tell one computer book from another, Manning celebrates the inventiveness and initiative of the computer business with book covers based on the right diversity of national costumes (...)

Good to know!

### Not a book for beginners

The book is advertised for users at an "intermediate to advanced level".
One thing that clearly shows this is that the content on "Why you should use version control and how to convince others that doing so is a good idea" is an Appendix!
Note that the content I'd actually use on the topic is the article ["Excuse me, do you have a moment to talk about version control?" by Jenny Bryan](https://peerj.com/preprints/3159/).

### An older book?

The book was published in 2015.
I guess some Git things have been deprecated but I assume most of the book is still valid.
What aged really bad: the screenshots from GitHub interface!

### 66 "techniques"

The book cover indicates it includes 66 techniques.
The first techniques are Git init, Git add, Git commit: calling them techniques is a bit of a stretch to me?
But then the very predictable structure of the book content was actually great, so using that structure from the get go wasn't bad at all.

## Chapter 1: Local Git

### Clearer understanding of Git add

> "Rather than require all changes in the working tree to make up the next commit, Git allows files to be added incrementally to the index"

So, while I've been practicing this, I'm not sure I ever expressed the usefulness of Git add.

I also underlined a sentence explaining that git add does two things:

> "git add is used both to initially add a file to the Git repository and to request that changes to the fine be used in the next commit."

### Garbage in, garbage out

I liked that sentence:

> "How useful the history is relies a great deal on the quality of data entered into it."

Then the author mentions two reasons why small commits are better:

- Better readability of the history;
- Easier reversal of an unwanted change.

### Commit messages are structured like emails

And apparently this comes from the history of Git, where commits could be sent as email.
So the first line of a commit message is the subject and the rest, the body.

I guess there's also a parallel between conventional commits convention, where you add a prefix to the subject indicating its category: "fix:" for bug fixes, "feat:" for features, is like adding a prefix to an email subject: "[ACTION REQUIRED]".

### A motivation for rewriting history

> "there's no need for everyone to see the mistakes you made along the way"

Now let's see if this, and other parts of the book, motivate me enough to rewrite the history of my Git branches before I mark a PR as ready for review.