---
title: "Three useful (to me) R notions"
date: '2023-07-24'
tags:
  - good practice
  - code style
slug: basic-patterns
output: hugodown::hugo_document
---

Following my recent post on [three useful (to me) R patterns](/2023/06/06/basic-patterns/), I've written down three other things on a tiny sticky note.
This post will allow me to throw away this beaten down sticky note, and maybe to show you one element you didn't know?

## `nzchar()`: a fast way to find out if elements of a character vector are non-empty strings

One of my favorite testing technique is the escape hatch strategy, about which I wrote a [post on the R-hub blog](https://blog.r-hub.io/2023/01/23/code-switch-escape-hatch-test/): you make part of your code responsive to an environment variable, and you locally set that environment variable in your tests.
In your code, to determine whether the environment variable has been set to something, anything, you can use the `nzchar()` function.

```{r}
nzchar("Hello World")
nzchar("")
nzchar(NA)
nzchar(NA, keepNA = TRUE)

# Now with an environment variable
nzchar(Sys.getenv("blopblopblop"))
withr::with_envvar(
  "blopblopblop" = "bla",
  nzchar(Sys.getenv("blopblopblop"))
)
```

Allow me to mention the obvious: if you're using `nzchar()` to examine an environment variable, do not forget `Sys.getenv()`.
I spent too much time looking at the following piece of code last week: `nzchar("BABELQUARTO_TESTS_URL")` wondering why it didn't do what I expected it to do... I had to replace it with `nzchar(Sys.getenv("BABELQUARTO_TESTS_URL"))`.


[^three]: I am aware that the idea of "three things" can remind of Nick Tierney's ["Just three things" format](https://www.njtierney.com/post/2019/02/18/announcing-jtt/). What a nice idea of his and Karthik Ram's.