on:
  push:
    branches: 
      - master
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '12 0 1 * *'
      
jobs:  
  hugo-update:
    name: hugo-update
    runs-on: ubuntu-latest

    steps:    
    - uses: actions/checkout@v2
      
    - name: Updating
      run: |
          ov=$(grep 'HUGO_VERSION' netlify.toml -m 1 | grep -o -P '(?<=HUGO\_VERSION[[:space:]]\=[[:space:]]\").*(?=\")')
          nv=$(curl --request GET \
          --url https://api.github.com/repos/gohugoio/hugo/releases/latest \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          | jq --raw-output .name)
          nv=${nv#v}
          if [ $ov != $nv ]
            then
              git config --global user.email "example@example.com"
              git config --global user.name "gh-pages committer"
              git checkout -b "hugo-update$nv"
              sedp="s/HUGO_VERSION\s=\s\"$ov\"/HUGO_VERSION \= \"$nv\"/g" 
              sed -i "$sedp" netlify.toml
              git commit netlify.toml -m 'Update Hugo' || echo "No changes to commit"
              git push --set-upstream origin "hugo-update$nv"
              curl --request POST \
              --data '{"title": "Update Hugo", "body": "Please pull these awesome changes in!", "head": "${{ github.repository_owner }}:hugo-update$nv", "base": "master" }' \
              --url https://api.github.com/repos/${{ github.repository }}/pulls \
              --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}'
           else
             echo "Hugo already up-to-date in the Netlify config! :-)"  
          fi
