name: Main testing workflow
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron:  '0 12 * * 1'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Actions Repository
      uses: actions/checkout@v2
    - name: Test GitHub Action
      uses: ./
      with: 
        git_path: https://github.com/urlstechie/urlchecker-test-repo
        file_types: .m
        timeout: 5
        retry_count: 3
        white_listed_urls: https://github.com/SuperKogito/URLs-checker/issues/1,https://github.com/SuperKogito/URLs-checker/issues/2
        white_listed_patterns: https://github.com/SuperKogito/Voice-based-gender-recognition/issues
        white_listed_files: README.md
