name: Main testing workflow
on:
  schedule:
    - cron:  '0 12 1 * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: URLs-checker
      uses: urlstechie/urlchecker-action@0.1.8
      with:
        # A comma-separated list of file types to cover in the URL checks
        file_types: .md
        key:  
        # Choose whether to include file with no URLs in the prints.
        print_all: False# A comma separated list of file patterns (direct paths work as well) to exclude
        white_listed_files: /content/post/2018-03-24-satrdaycapetown.md,/content/post/2018-03-04-hrbrpkgs.md
