name: Main testing workflow
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron:  '0 12 * * 1'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: URLs-checker
      uses: SuperKogito/URLs-checker@0.1.2
      with:
        # The project base path.
        git_path: https://github.com/maelle/simplymaelle

        # A comma-separated list of file types to cover in the URL checks
        file_types: .md
        key:  
        # Choose whether to include file with no URLs in the prints.
        print_all: False
